In [1]:
from datetime import datetime
import pandas as pd
from alpaca.data.historical import CryptoHistoricalDataClient,StockHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest,StockLatestTradeRequest
from alpaca.data.timeframe import TimeFrame

In [2]:
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import GetAssetsRequest
import hayai_util

context = hayai_util.create_context('medium_tech_usa')

trading_client = TradingClient(context['api_key'], context['secret_key'], paper=True)

# Get our account information.
account = trading_client.get_account()

# Check if our account is restricted from trading.
if account.trading_blocked:
    print('Account is currently restricted from trading.')

# Check how much money we can use to open new positions.
print('${} is available as buying power.'.format(account.buying_power))
account

$116429.76 is available as buying power.

{   'account_blocked': False,
    'account_number': 'PA3KM7I3YKDN',
    'accrued_fees': '0',
    'buying_power': '116429.76',
    'cash': '95288.7',
    'created_at': datetime.datetime(2026, 2, 22, 15, 18, 10, 188300, tzinfo=TzInfo(0)),
    'crypto_status': <AccountStatus.ACTIVE: 'ACTIVE'>,
    'currency': 'USD',
    'daytrade_count': 1,
    'daytrading_buying_power': '0',
    'equity': '99815.12',
    'id': UUID('ec53c810-895b-46ba-97ea-9814fbd99da1'),
    'initial_margin': '41600.24',
    'last_equity': '99175.58361923925',
    'last_maintenance_margin': '26654.9',
    'long_market_value': '41878.96',
    'maintenance_margin': '26547.74',
    'multiplier': '2',
    'non_marginable_buying_power': '57936.16',
    'options_approved_level': 3,
    'options_buying_power': '58214.87',
    'options_trading_level': 3,
    'pattern_day_trader': False,
    'pending_transfer_in': None,
    'pending_transfer_out': None,
    'portfolio_value': '99815.12',
    'regt_buying_power': '116429.76',
    'short_market_value': '-37352.54',
    'shorting_enabled': True,
    'sma': '99406.25',
    'status': <AccountStatus.ACTIVE: 'ACTIVE'>,
    'trade_suspended_by_user': False,
    'trading_blocked': False,
    'transfers_blocked': False}

In [3]:



# Get a list of all of our positions.
portfolio = trading_client.get_all_positions()

df = pd.DataFrame([position.__dict__ for position in portfolio])
df['qty'] = df['qty'].astype(float)
df['market_value'] = df['market_value'].astype(float)
df['current_price'] = df['current_price'].astype(float)
df = df[['symbol', 'qty', 'market_value', 'current_price']]
df['market_value'].sum(),df[df['market_value']>0]['market_value'].sum(),df[df['market_value']<0]['market_value'].sum()

(np.float64(4526.416679),
 np.float64(41878.956678999995),
 np.float64(-37352.54))

Prezzo quando compro: ask
Prezzo quando vendo: bid
Usare la media dei due

In [6]:
lsr = StockLatestTradeRequest(symbol_or_symbols=['AAPL', 'MSFT', 'GOOG'])
client = StockHistoricalDataClient(context['api_key'], context['secret_key'])
result =client.get_stock_latest_trade(lsr)
pd.DataFrame(result)

,MSFT,AAPL,GOOG
0,"(symbol, MSFT)","(symbol, AAPL)","(symbol, GOOG)"
1,"(timestamp, 2026-03-03 21:51:42.607071+00:00)","(timestamp, 2026-03-03 20:59:59.382090+00:00)","(timestamp, 2026-03-03 20:59:59.900215+00:00)"
2,"(exchange, V)","(exchange, V)","(exchange, V)"
3,"(price, 403.79)","(price, 263.75)","(price, 303.49)"
4,"(size, 100.0)","(size, 107.0)","(size, 100.0)"
5,"(id, 17851)","(id, 20281)","(id, 7390)"
6,"(conditions, [@, T])","(conditions, [@])","(conditions, [@])"
7,"(tape, C)","(tape, C)","(tape, C)"

In [15]:
prices = {k: v.price for k, v in result.items()}
pd.DataFrame(list(prices.items()), columns=['symbol', 'price'])

  symbol   price
0   MSFT  403.79
1   AAPL  263.75
2   GOOG  303.49

In [16]:
account = trading_client.get_account()
account

{   'account_blocked': False,
    'account_number': 'PA3KM7I3YKDN',
    'accrued_fees': '0',
    'buying_power': '116219.11',
    'cash': '95288.7',
    'created_at': datetime.datetime(2026, 2, 22, 15, 18, 10, 188300, tzinfo=TzInfo(0)),
    'crypto_status': <AccountStatus.ACTIVE: 'ACTIVE'>,
    'currency': 'USD',
    'daytrade_count': 1,
    'daytrading_buying_power': '0',
    'equity': '99739.11',
    'id': UUID('ec53c810-895b-46ba-97ea-9814fbd99da1'),
    'initial_margin': '41629.56',
    'last_equity': '99175.58361923925',
    'last_maintenance_margin': '26654.9',
    'long_market_value': '41870.27',
    'maintenance_margin': '26565.33',
    'multiplier': '2',
    'non_marginable_buying_power': '57868.84',
    'options_approved_level': 3,
    'options_buying_power': '58109.55',
    'options_trading_level': 3,
    'pattern_day_trader': False,
    'pending_transfer_in': None,
    'pending_transfer_out': None,
    'portfolio_value': '99739.11',
    'regt_buying_power': '116219.11',
    'short_market_value': '-37419.86',
    'shorting_enabled': True,
    'sma': '99406.25',
    'status': <AccountStatus.ACTIVE: 'ACTIVE'>,
    'trade_suspended_by_user': False,
    'trading_blocked': False,
    'transfers_blocked': False}